export const REQUEST_BEERS = 'REQUEST_BEERS';
export const RECEIVE_BEERS = 'RECEIVE_BEERS';
export const BOOKMARK = 'BOOKMARK';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const FILTER_BY_STRENGTH = 'FILTER_BY_STRENGTH';
export const FILTER_BY_BOOKMARK = 'FILTER_BY_BOOKMARK';

